version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: campus_lite
      MYSQL_USER: campus_user
      MYSQL_PASSWORD: campus_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
